### ISSUE TITLE
Unify behavior of plastic strain without or with transports

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-core#151]
**Summary**

I consider the fact that PyRolL switches the way the plastic strain is treated based on the fact whether a transport is present or not a severe design flaw. Without transport plastic strain is accumulated with transport present it is reset to zero between stands.

As it seems to be an accepted assumption that for most materials recrystallization occurs between stands this should be the default PyRolL-behavior regardless whether transports are present.

It should be possible for the user to request accumulative plastic strain via a PyRolL-setting.

**Comment by axtimhaus** [comment]
There is no behavior switched because of present or not present transports. The transport itself resets the strain to 0 by default (assuming total recrystallization within the transport).

We do not think, that it is a design flaw, since without a transport (aka inter-pass range) between there would be immediate input from the previous pass to the next (which is of course physically not possible). So where shall the recrystallization happen?
We designed it to model the inter-pass ranges explicitly as a transport unit, rather than implicitly.

So this behavior will not be changed.

**Comment by ChRen95** [comment]
Agreeing with @axtimhaus in that case. Our assumption tends to be wrong when higher rolling speeds are present.
