### ISSUE TITLE
WIndows 11: PyRoll-run gets stuck in an endless loop due to problems with kaleido package

### ISSUE THREAD

**Issue by GRPlan** [pyroll-project/pyroll-core#195]
**Summary**

After the update to Windows 11 PyRoll run got stuck in an endless loop.

Problem is caused by the kaleido package.

See 
https://github.com/plotly/Kaleido/issues/126
Plotly fig.to_image is stucking on windows 11. #126

Downgrading the kaleidoversion to kaleido==0.1.0post1 via pip worked for me.

**Comment by axtimhaus** [comment]
No we did not fix this.

**Comment by RichardPfr** [comment]
On my Windows 11 machine I do get the same issue when using the newest kaleido version and downgrading it to kaleido==0.1.0.post1 does also fix it for me. 

As this is a Problem specifically with either Windows 11 or the newest kaleido version I don't think there is much we can do besides requiring the use of the older kaleido version on all Windows 11 machines.

The comments in the kaleido issue given by @GRPlan hint at the same issue and as there have been no updates to kaleido in almost three years this is unlikely to be fixed.

Is there maybe an option on our side to check if this kaleido version is installed to only then use plotly and otherwise fall back on using matplotlib?

**Comment by ChRen95** [comment]
Your on the right track so create a branch from that issue and think of way to resolve this problem.
